markdown: rdiscount
auto: true

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test"]

owner-name: Bram Verbruggen
owner-email: bram.verbruggen@gmail.com

title: StreamQ

navigation:
- text: Home
  url: index.html
- text: Over Ons
  url: about.html
