markdown: rdiscount
auto: true

exclude: ["README.md", "LICENSE.md", "TODO.md", "build", "test"]

owner-name: Bram Verbruggen
owner-email: bram.verbruggen@streamq.be

title: StreamQ

navigation:
- text: Home
  url: /index.html
- text: Info
  url: /about.html
- text: Producten
  url: /products.html
- text: Blog
  url: /blog.html

license: &#0169; 2012 All rights reserved
